#!/usr/bin/env node
/**
 * cronagent - cron for AI coding agents.
 * CLI entry point: init | list | run <name> | start | report.
 */
import fs from "node:fs";
import path from "node:path";
import { loadConfig, type CronAgentConfig } from "./config.js";
import { nextRun } from "./cron.js";
import { buildReport } from "./report.js";
import { runJob } from "./runner.js";
import { startScheduler } from "./scheduler.js";
import { listRuns, fmtDuration, fmtDateTime } from "./store.js";

const VERSION = "0.1.0";

/* ------------------------------------------------------------------ */
/* ANSI colors (no deps; disabled when NO_COLOR or when not a TTY)       */
/* ------------------------------------------------------------------ */

const noColor = process.env.NO_COLOR !== undefined || !process.stdout.isTTY;
const wrap =
  (code: string) =>
  (s: string): string =>
    noColor ? s : `\u001b[${code}m${s}\u001b[0m`;
const bold = wrap("1");
const dim = wrap("2");
const red = wrap("31");
const green = wrap("32");
const yellow = wrap("33");
const cyan = wrap("36");

/* ------------------------------------------------------------------ */
/* Help                                                                 */
/* ------------------------------------------------------------------ */

function printHelp(): void {
  console.log(`cronagent ${VERSION} - cron for AI coding agents

Usage: cronagent <command> [options]

Commands:
  init                 Write a demo cronagent.yaml in the current directory
  list                 List jobs: schedule, enabled, next run, last status
  run <name>           Run one job now (ignores the schedule), print output tail
  start                Start the scheduler loop (Ctrl+C to stop)
  report               Generate .cronagent/report.html from recent runs

Options:
  --config <path>      Config file to use
                       (default search: ./cronagent.yaml, ~/.config/cronagent/config.yaml)
  -h, --help           Show this help (or command-specific help after a command)
  -v, --version        Show version

Run data is archived under .cronagent/ next to the config file.`);
}

/* ------------------------------------------------------------------ */
/* init                                                                 */
/* ------------------------------------------------------------------ */

const DEMO_CONFIG = `# cronagent - cron for AI coding agents
# Generated by \`cronagent init\`. See cronagent.example.yaml for more examples.

agentDefaults:
  timeoutMinutes: 30        # default kill-timeout for jobs (per-job timeoutMinutes overrides)

jobs:
  # Demo job using the bundled fake agent (demo/fake-agent.js) so everything
  # works without installing a real coding agent. Swap the agent: line to go live.
  - name: demo-job
    schedule: "*/2 * * * *" # every second minute
    prompt: "Check package.json for outdated deps; open a branch with safe upgrades."
    agent: 'node demo/fake-agent.js "{{prompt}}"'
    enabled: true

  # Real agent example:
  # - name: bump-deps
  #   schedule: "0 9 * * 1" # Mondays 09:00
  #   prompt: "Check package.json for outdated deps; open a branch with safe upgrades."
  #   agent: 'claude -p "{{prompt}}"'
  #   cwd: ../myrepo
`;

function cmdInit(args: string[]): number {
  if (args[0] === "-h" || args[0] === "--help") {
    console.log("Usage: cronagent init\n\nWrite a cronagent.yaml with a working demo job in the current directory.");
    return 0;
  }
  const target = path.resolve(process.cwd(), "cronagent.yaml");
  if (fs.existsSync(target)) {
    console.error(yellow(`cronagent.yaml already exists: ${target}`));
    console.error("Delete it first, or point --config somewhere else.");
    return 1;
  }
  fs.writeFileSync(target, DEMO_CONFIG, "utf8");
  console.log(green(`Wrote ${target}`));
  console.log(`
Next steps:
  1. cronagent list            # see the demo job and its next run
  2. cronagent run demo-job    # run it once, right now
  3. cronagent start           # start the scheduler (Ctrl+C to stop)
  4. cronagent report          # generate .cronagent/report.html

The demo job shells out to \`node demo/fake-agent.js\` (bundled with cronagent) so
everything works without a real agent installed. To go live, edit the agent:
field, e.g.  agent: 'claude -p "{{prompt}}"'  (see cronagent.example.yaml).`);
  return 0;
}

/* ------------------------------------------------------------------ */
/* list                                                                 */
/* ------------------------------------------------------------------ */

function cmdList(config: CronAgentConfig): number {
  const header = ["JOB", "SCHEDULE", "ENABLED", "NEXT RUN", "LAST STATUS"];
  const rows = config.jobs.map((job) => {
    let next: string;
    try {
      next = fmtDateTime(nextRun(job.parsedSchedule, new Date())).slice(0, 16);
    } catch {
      next = "never";
    }
    const last = listRuns(config, job.name, 1)[0]?.status ?? "-";
    return [job.name, job.schedule, job.enabled ? "yes" : "no", next, last];
  });
  const widths = header.map((h, i) => Math.max(h.length, ...rows.map((r) => r[i].length)));
  const paddedHeader = header.map((h, i) => h.padEnd(widths[i] as number)).join("  ");
  console.log(bold(paddedHeader));
  for (const row of rows) {
    const cells = row.map((c, i) => c.padEnd(widths[i] as number));
    let statusCell = cells[4] as string;
    if (row[4] === "success") statusCell = green(statusCell);
    else if (row[4] === "failed") statusCell = red(statusCell);
    else if (row[4] === "timeout") statusCell = yellow(statusCell);
    const enabledCell = row[2] === "yes" ? (cells[2] as string) : dim(cells[2] as string);
    console.log([cells[0], cells[1], enabledCell, cells[3], statusCell].join("  "));
  }
  console.log(`\n${config.jobs.length} job(s) - config: ${dim(config.configPath)}`);
  return 0;
}

/* ------------------------------------------------------------------ */
/* run                                                                  */
/* ------------------------------------------------------------------ */

function readTail(file: string, maxChars = 4096, maxLines = 30): string {
  let text: string;
  try {
    text = fs.readFileSync(file, "utf8");
  } catch {
    return "";
  }
  let prefix = "";
  if (text.length > maxChars) {
    text = text.slice(-maxChars);
    prefix = "[...]\n";
  }
  return prefix + text.split(/\r?\n/).slice(-maxLines).join("\n");
}

async function cmdRun(config: CronAgentConfig, args: string[]): Promise<number> {
  if (!args[0] || args[0] === "-h" || args[0] === "--help") {
    console.log("Usage: cronagent run <job-name>\n\nRun one job immediately (schedule is ignored) and print the tail of its output.");
    return args[0] ? 0 : 1;
  }
  const name = args[0] as string;
  const job = config.jobs.find((j) => j.name === name);
  if (!job) {
    console.error(red(`No job named "${name}" in ${config.configPath}`));
    console.error(`Available jobs: ${config.jobs.map((j) => j.name).join(", ")}`);
    return 1;
  }
  console.log(cyan(`cronagent: running "${name}" (timeout ${job.timeoutMinutes} min) ...`));
  const rec = await runJob(job, config);
  const tail = readTail(path.join(rec.runDir, "output.txt"));
  if (tail !== "") console.log(dim(`--- output tail ---\n${tail}`));
  const colorOf = rec.status === "success" ? green : rec.status === "timeout" ? yellow : red;
  console.log(`\ncronagent: ${colorOf(rec.status)} - exit ${rec.exitCode ?? "n/a"}, ${fmtDuration(rec.durationMs)}`);
  console.log(`run dir: ${rec.runDir}`);
  return rec.status === "success" ? 0 : 1;
}

/* ------------------------------------------------------------------ */
/* report                                                               */
/* ------------------------------------------------------------------ */

function cmdReport(config: CronAgentConfig): number {
  const outPath = buildReport(config);
  const count = listRuns(config, undefined, 500).length;
  console.log(green(`Report written: ${outPath}`));
  console.log(`Includes ${count} archived run(s). Open the file in a browser for totals, per-job stats and the last-7-days chart.`);
  return 0;
}

/* ------------------------------------------------------------------ */
/* main dispatch                                                        */
/* ------------------------------------------------------------------ */

function loadOrThrow(configFlag?: string): CronAgentConfig {
  const config = loadConfig(configFlag);
  for (const w of config.warnings) console.error(yellow(`[warn] ${w}`));
  return config;
}

async function main(argv: string[]): Promise<number> {
  let configFlag: string | undefined;
  const rest: string[] = [];
  for (let i = 0; i < argv.length; i++) {
    const a = argv[i] as string;
    if (a === "--config" || a === "-c") {
      configFlag = argv[++i];
      if (!configFlag) {
        console.error(red("--config requires a file path"));
        return 1;
      }
    } else if (a.startsWith("--config=")) {
      configFlag = a.slice("--config=".length);
    } else {
      rest.push(a);
    }
  }
  const cmd = rest[0];
  const args = rest.slice(1);

  if (cmd === undefined) {
    printHelp();
    return 1;
  }
  if (cmd === "-h" || cmd === "--help" || cmd === "help") {
    printHelp();
    return 0;
  }
  if (cmd === "-v" || cmd === "--version" || cmd === "version") {
    console.log(`cronagent ${VERSION}`);
    return 0;
  }

  switch (cmd) {
    case "init":
      return cmdInit(args);
    case "list": {
      if (args[0] === "-h" || args[0] === "--help") {
        console.log("Usage: cronagent list\n\nList all jobs with schedule, enabled flag, next run and last status.");
        return 0;
      }
      return cmdList(loadOrThrow(configFlag));
    }
    case "run":
      return cmdRun(loadOrThrow(configFlag), args);
    case "start": {
      if (args[0] === "-h" || args[0] === "--help") {
        console.log("Usage: cronagent start\n\nStart the scheduler loop. Ticks every 20s, fires matching jobs, Ctrl+C to stop.");
        return 0;
      }
      startScheduler(loadOrThrow(configFlag));
      return 0;
    }
    case "report": {
      if (args[0] === "-h" || args[0] === "--help") {
        console.log("Usage: cronagent report\n\nWrite .cronagent/report.html from the archived runs and print the path.");
        return 0;
      }
      return cmdReport(loadOrThrow(configFlag));
    }
    default:
      console.error(red(`Unknown command: ${cmd}\n`));
      printHelp();
      return 1;
  }
}

main(process.argv.slice(2)).then(
  (code) => {
    process.exitCode = code;
  },
  (err) => {
    console.error(red(`cronagent: error: ${err instanceof Error ? err.message : String(err)}`));
    process.exitCode = 1;
  },
);
